doc: update openai-models.md for 4o / missing yaml key
Update the output of `llm models` for recent 4x models and update `extra-openai-models.yaml` to demonstrate use of gpt-4o-2024-08-06.

Also, the example of `extra-openai-models.yaml` was missing `model_name` which leads to a KeyError:

```
  File "xxxx/llm/default_plugins/openai_models.py", line 53, in register_models
    model_name = extra_model["model_name"]
KeyError: 'model_name'
```